/*
 * embedded_assets.c — Generated file mapping URL paths to embedded bytes.
 * DO NOT EDIT — regenerated by scripts/embed-frontend.sh
 */
#include "ui/embedded_assets.h"
#include <string.h>

extern const unsigned char _binary_assets_index_D1_3bntm_css_start[];
extern const unsigned char _binary_assets_index_D1_3bntm_css_end[];
extern const unsigned char _binary_assets_index_urRrcEH6_js_start[];
extern const unsigned char _binary_assets_index_urRrcEH6_js_end[];
extern const unsigned char _binary_index_html_start[];
extern const unsigned char _binary_index_html_end[];

cbm_embedded_file_t CBM_EMBEDDED_FILES[] = {
    {"/assets/index-D1-3bntm.css", _binary_assets_index_D1_3bntm_css_start, 0, "text/css"},
    {"/assets/index-urRrcEH6.js", _binary_assets_index_urRrcEH6_js_start, 0, "application/javascript"},
    {"/index.html", _binary_index_html_start, 0, "text/html"},
};
const int CBM_EMBEDDED_FILE_COUNT = 3;

static void __attribute__((constructor)) init_embedded_sizes(void) {
    cbm_embedded_file_t *files = CBM_EMBEDDED_FILES;
    files[0].size = (unsigned int)(_binary_assets_index_D1_3bntm_css_end - _binary_assets_index_D1_3bntm_css_start);
    files[1].size = (unsigned int)(_binary_assets_index_urRrcEH6_js_end - _binary_assets_index_urRrcEH6_js_start);
    files[2].size = (unsigned int)(_binary_index_html_end - _binary_index_html_start);
}

const cbm_embedded_file_t *cbm_embedded_lookup(const char *path) {
    for (int i = 0; i < CBM_EMBEDDED_FILE_COUNT; i++) {
        if (strcmp(CBM_EMBEDDED_FILES[i].path, path) == 0) {
            return &CBM_EMBEDDED_FILES[i];
        }
    }
    return NULL;
}
