/*
 * embedded_skills.h — Types and declarations for embedded skill assets.
 *
 * The actual data lives in embedded_skills.c, which is generated by
 * scripts/embed-skills.sh from .md files under assets/skills/.
 */
#ifndef CBM_EMBEDDED_SKILLS_H
#define CBM_EMBEDDED_SKILLS_H

/* A single file within a skill directory. */
typedef struct {
    const char *rel_path; /* e.g. "SKILL.md" or "references/quality.md" */
    const char *content;  /* null-terminated file content */
} cbm_skill_file_t;

/* ── codebase-memory skill ──────────────────────────────────────── */

/* SKILL.md content (primary skill file). */
extern const char cbm_embedded_skill_content[];

/* All files for this skill (NULL-terminated: last entry has rel_path==NULL). */
extern const cbm_skill_file_t cbm_embedded_skill_files[];

#endif /* CBM_EMBEDDED_SKILLS_H */
