#!/bin/bash
# embed-skills.sh — Convert skill .md files into C string literals.
#
# Usage: scripts/embed-skills.sh <skill_assets_dir> <output_c_file>
#
# Reads .md files from skill_assets_dir (e.g. assets/skills/codebase-memory/)
# and generates a C source file with string literals for each file.
#
# The first file named SKILL.md is exported as cbm_embedded_skill_content[].
# All files are listed in the cbm_embedded_skill_files[] array (NULL-terminated).

set -euo pipefail

ASSETS_DIR="${1:?Usage: embed-skills.sh <skill_assets_dir> <output_c_file>}"
OUTPUT_C="${2:?Usage: embed-skills.sh <skill_assets_dir> <output_c_file>}"

# Strip trailing slash
ASSETS_DIR="${ASSETS_DIR%/}"

# Collect all .md files, sorted for deterministic output
FILES=()
while IFS= read -r -d '' file; do
    FILES+=("$file")
done < <(find "$ASSETS_DIR" -name '*.md' -type f -print0 | sort -z)

if [[ ${#FILES[@]} -eq 0 ]]; then
    echo "Error: no .md files found in $ASSETS_DIR" >&2
    exit 1
fi

# Mangle a relative path into a valid C identifier
mangle() {
    echo "$1" | sed 's/[^a-zA-Z0-9]/_/g'
}

# Escape a text file into C string literal continuation lines.
# Each line becomes:     "escaped line\n"
emit_c_string_lines() {
    local file="$1"
    sed \
        -e 's/\\/\\\\/g' \
        -e 's/"/\\"/g' \
        -e 's/	/\\t/g' \
        -e 's/^/    "/' \
        -e 's/$/\\n"/' \
        "$file"
}

# ── Generate C source ───────────────────────────────────────────────

{
    cat <<'HEADER'
/*
 * embedded_skills.c — Generated file with skill .md content as C strings.
 * DO NOT EDIT — regenerated by scripts/embed-skills.sh
 */
#include "cli/embedded_skills.h"

HEADER

    # Find SKILL.md (must exist)
    SKILL_MD=""
    for file in "${FILES[@]}"; do
        rel="${file#$ASSETS_DIR/}"
        if [[ "$rel" == "SKILL.md" ]]; then
            SKILL_MD="$file"
            break
        fi
    done

    if [[ -z "$SKILL_MD" ]]; then
        echo "Error: no SKILL.md found in $ASSETS_DIR" >&2
        exit 1
    fi

    # Emit SKILL.md as the public symbol
    echo "/* Primary skill file: SKILL.md */"
    echo "const char cbm_embedded_skill_content[] ="
    emit_c_string_lines "$SKILL_MD"
    echo ";"
    echo ""

    # Emit reference files as static symbols
    for file in "${FILES[@]}"; do
        rel="${file#$ASSETS_DIR/}"
        [[ "$rel" == "SKILL.md" ]] && continue
        mangled=$(mangle "$rel")
        echo "/* $rel */"
        echo "static const char content_${mangled}[] ="
        emit_c_string_lines "$file"
        echo ";"
        echo ""
    done

    # Emit the file list array (NULL-terminated)
    echo "const cbm_skill_file_t cbm_embedded_skill_files[] = {"
    for file in "${FILES[@]}"; do
        rel="${file#$ASSETS_DIR/}"
        if [[ "$rel" == "SKILL.md" ]]; then
            echo "    {\"$rel\", cbm_embedded_skill_content},"
        else
            mangled=$(mangle "$rel")
            echo "    {\"$rel\", content_${mangled}},"
        fi
    done
    echo "    {0, 0} /* sentinel */"
    echo "};"

} > "$OUTPUT_C"

echo "Generated $OUTPUT_C with ${#FILES[@]} embedded skill files"
